server:
  port: 18080

logging:
  level:
    cn.sixlab.mbx: debug

spring:
  mvc:
    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mbx?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
#    password:
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
#    sentinel:
#      master:
#      nodes:
    timeout: 5000ms
  thymeleaf:
    cache: false
    mode: HTML5
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  mail:
    default-encoding: utf-8
    host: smtp.XXXX.cn`
    username: XXX@XXX.cn
    password: XXXXXXX
    protocol: smtps
    port: 465
    properties:
      mail:
        debug: false
        smpt:
          timeout: 30000
          starttls:
            enable: false
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-durations-as-timestamps: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    time-zone: GMT+8
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb

mbx:
  version: '@project.version@'
  jwt:
    header: Authorization
    secret: Sixlab's Mbx
    expiration: 604800000
    bearer: Bearer-
  domain:
    sub:
      blog: ms
      lx: lx
      api: api
  webhooks:
    github: 1
    gitee: 1
  hexo:
    path: /Users/patrick/six_myspace/PatrickRoot.github.io
